services:
  cortana-discord-bot:
    image: ghcr.io/tristanpadiou/cortana_discord_bot:latest
    container_name: cortana-discord-bot
    pull_policy: always
    networks:
      - cortana-network

    volumes:
      # Persist logs and data
      - ./logs:/app/logs:rw
      - ./data:/app/data:rw

    environment:
      - PYTHONUNBUFFERED=1
      - CORTANA_API_URL=http://cortana-api:8000
      # These will be overridden by environment variables passed from GitHub Actions
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - BOT_TOKEN=${BOT_TOKEN}
      - DISCORD_SERVER_ID=${DISCORD_SERVER_ID}
      - BEARER_TOKEN=${BEARER_TOKEN}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import os; exit(0 if os.getenv('BEARER_TOKEN') and os.getenv('DISCORD_TOKEN') else 1)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  cortana-network:
    external: true
    name: cortana_api_cortana-network

volumes:
  cortana-discord-bot-logs:
  cortana-discord-bot-data:
