services:
  cortana-discord-bot:
    build: .
    container_name: cortana-discord-bot
    networks:
      - cortana-network

    volumes:
      # Persist logs and data
      - ./logs:/app/logs:rw
      - ./data:/app/data:rw

    env_file:
      - .env
    environment:
      - PYTHONUNBUFFERED=1
      - CORTANA_API_URL=http://cortana-api:8000
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import os; exit(0 if os.getenv('BEARER_TOKEN') and os.getenv('DISCORD_TOKEN') else 1)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  cortana-network:
    external: true
    name: cortana_api_cortana-network

volumes:
  cortana-discord-bot-logs:
  cortana-discord-bot-data: